FROM python:3
# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Setting Work directory for RUN CMD commands
WORKDIR /code
#Copy requirements file from current directory to file in
#containers code directory we have just created.
COPY requirements.txt requirements.txt

#Run and install all required modules in container
RUN pip install -r requirements.txt

#Copy current directory files to containers code directory
COPY . .
